import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Space_Grotesk } from "next/font/google";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"], // You can change this if you need other character sets
  weight: ["300", "400", "500", "600", "700"], // Specify the font weights you need
  variable: "--font-space-grotesk", // Define a CSS variable for easier usage
});

export const metadata: Metadata = {
  title: "Anvika Industries ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable} antialiased`}>
        <header>
          <Navbar />
        </header>
        <div className="pt-[50px] p-2">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
